### ISSUE TITLE
Snes ,gba and nes don’t work 5.0.2

### ISSUE THREAD

**Issue by cad1112** [Jan4V/hekate-ipl-50x#8]
Snes ,gba and nes emulators don’t open in homebrew launcher fw 5.0.2

**Comment by tgdnix** [comment]
This is a known issue for 5.0.2.
Most Homebrew apps don't work at all, except for pFBA, and others, like nxengine, crashes the Switch completely.

**Comment by Arch9SK7** [comment]
This isnt an issue of his bootloader it is the libnx build isnt updated yet for 5.0.X yet so most apps built using the older code will be obsolete. Not an issue here @Jan4V please close?

**Comment by swoozi** [comment]
i hope they will be updating the emulators soon.

**Comment by tgdnix** [comment]
@Arch9SK7 
I know this isn't related, but I thought it would be worth mentioning:
The RetroArch cores aren't based on libnx, but rather libtransistor, so that's what would need to be updated.
It would probably be easier to base them on libnx for easier updating, but this would require building the emulators from the ground up

**Comment by substanc3-dev** [comment]
The emulators need to be updated with latest libnx/libtransistor.
